#CRIANDO MAKE

CC = g++

CPPFLAGS = -Wall

BPG: func.o main.o 
	@$(CC) $(CPPFLAGS) -std=c++11 func.o main.o -o BPG
	@echo "Bingo!!! Tabuleiros criados"

main.o: mainr.cpp
	@$(CC) $(CPPFLAGS) -std=c++11 -c main.cpp
	@echo "Criando seu tabuleiro..."
func_.o: func.cpp
	@$(CC) $(CPPFLAGS) -std=c++11 -c func.cpp
	@echo "Chamando as funções meu patrão"
clean:
	@rm -rf *o BPG
	@echo "Diretorio limpo"
